[package]
name = "echor"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }

[dev-dependencies]
assert_cmd = { version = "2.0.14" }
predicates = { version = "3.1.0" }
